# Generated by Django 3.0.5 on 2020-04-07 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sticky',
            name='slug',
            field=models.CharField(max_length=7),
        ),
    ]
