# Generated by Django 3.0.5 on 2020-04-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0002_auto_20200407_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sticky',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
